### ISSUE TITLE
main: Ifa determinism gate red — pinned NornicDB source UI stage fails tsc (TS2882)

### ISSUE THREAD

**Issue by linuxdynasty** [eshu-hq/eshu#6505]
## Summary

`main` is red: the Ifa Determinism Gate (determinism-matrix, and by the same build every other image-building job in that workflow) fails building the pinned NornicDB source. Upstream `orneryd/NornicDB@3722b483`'s `docker/Dockerfile.cpu-bge` UI stage runs `npm run build` (`tsc && vite build`) which fails with TS2882 on side-effect CSS imports (`./Bifrost.css`, `./index.css`). Eshu has no `ui/` or `docker/` of its own — the entire failure is upstream's tree at our pin plus our default from-source build policy.

## Evidence

- Ifa Determinism Gate run 33804850327, job 100812753233: `Bifrost/Bifrost.tsx(4,8): error TS2882`, `src/main.tsx(4,8): error TS2882`, same workflow failed on `main@29b91b8a39` before any of the current lane PRs pushed.
- The pin (`3722b483`, with `Dockerfile.cpu-bge` from-source build) was introduced in b064f8e3e (#6448 era); sibling workflows (golden-corpus, e2e, value-flow, frontend) stay green because they do not build this image from source.
- Upstream's own Dockerfile documents the escape hatch: `--build-arg HEADLESS=true` skips the UI stage. No eshu gate serves the NornicDB UI, so nothing the gate proves depends on that bundle.

## Proposed fix

Thread the upstream `HEADLESS` build arg through eshu's compose (`args: HEADLESS: ${NORNICDB_HEADLESS:-false}`, local default unchanged) and set `NORNICDB_HEADLESS=true` on the image-building jobs in `ifa-determinism-gate.yml`. Docs updated for the new env knob. The TS2882 itself is upstream's to fix; this unblocks `main` without waiting on them and without moving the backend pin (whose #261/#290 fixes stay put).
